### ISSUE TITLE
Doubly-nested classes without keys at each level breaks codegen

### ISSUE THREAD

**Issue by nanodeath** [nanodeath/TypedConfig#119]
If I have a key like this:

```toml
['database.jdbc.url']
type = "str"
```

without any keys directly under `database`, the generated Database class will be missing generated methods like `validate` and `getAllKeys`.
